# ── UniFi Network Application ─────────────────────────────────────────────────
# The controller container, its MongoDB backend, and the DHCP wiring that lets
# factory-default access points find it.
#
# Three decisions here are load-bearing and easy to "fix" into breakage:
#
#   1. The controller runs on the HOST network, not a bridge. Device discovery
#      is UDP broadcast on 10001 and 1900, which a NAT'd podman bridge does not
#      deliver, and a bridge would also make every AP appear to come from the
#      bridge gateway. Host networking also means no firewall change is needed
#      at all — modules/firewall.nix already accepts everything from br-lan.
#
#   2. system.properties is rendered here rather than by the image. The
#      container only templates it when the file is absent, so its MONGO_* env
#      vars are first-run-only: with the image in charge, changing the database
#      password or host in Nix would silently do nothing forever. Writing the
#      file ourselves makes those ordinary Nix values. This is why /config is a
#      bind mount and not a named volume — an ExecStartPre has to reach it.
#
#   3. MongoDB is pinned to 4.4 and is reachable by nothing but this host. See
#      the `database.image` option description in modules/wireless.nix for the
#      full reasoning; the short version is that 5.0+ needs AVX, the target
#      hardware has none, and isolation is what covers 4.4 being end-of-life.
{
  config,
  lib,
  pkgs,
  ...
}:
with lib;
let
  cfg = config.router;
  wcfg = cfg.wireless.unifi;
  w = cfg._wirelessInternal;
  inherit (config.router._internal) lanGW;

  dbHost = w.unifi.ip 2;
  dbPort = 27017;

  # The four databases the controller expects. Guides that grant only
  # <name> and <name>_stat are stale: without _audit and _restore the
  # controller's audit log and its own backup/restore both fail.
  dbNames = [
    wcfg.database.name
    "${wcfg.database.name}_stat"
    "${wcfg.database.name}_audit"
    "${wcfg.database.name}_restore"
  ];

  # Runs once, against an empty data directory, as the image's initdb hook.
  #
  # A shell script rather than a .js one on purpose: the image runs *.js through
  # the legacy `mongo` shell, which has no way to read the environment, so the
  # password would have to be interpolated into the Nix store. Shell scripts get
  # the container's environment, so the secret stays in the env file. This is
  # also the shape LinuxServer's own init-mongo.sh uses.
  #
  # NOTE: /docker-entrypoint-initdb.d only executes on a first start with an
  # empty data directory. Rotating the password afterwards needs a manual
  # db.changeUserPassword().
  mongoInitScript = pkgs.writeShellScript "unifi-init-mongo.sh" ''
    set -euo pipefail
    mongo <<EOF
    use admin
    db.auth("$MONGO_INITDB_ROOT_USERNAME", "$MONGO_INITDB_ROOT_PASSWORD")
    db.createUser({
      user: ${builtins.toJSON wcfg.database.user},
      pwd: "$UNIFI_DB_PASSWORD",
      roles: [
        "clusterMonitor",
    ${concatMapStringsSep "\n" (n: ''{ db: ${builtins.toJSON n}, role: "dbOwner" },'') dbNames}
      ],
    })
    EOF
  '';

  configDir = "/var/lib/unifi-network-application";
  mongoDataDir = "/var/lib/unifi-mongo";

  # Rendered before every container start, so the values below track the Nix
  # config instead of being frozen at first boot. Fields and URI shape match
  # the image's own root/defaults/system.properties template.
  systemPropertiesScript = pkgs.writeShellScript "unifi-system-properties" ''
    set -euo pipefail
    umask 077
    install -d -m 0750 -o unifi -g unifi ${configDir} ${configDir}/data

    pass=$(cat ${w.stateDir}/mongo-unifi.pass)
    uri_base="mongodb://${wcfg.database.user}:$pass@${dbHost}:${toString dbPort}"

    tmp=$(mktemp)
    cat > "$tmp" <<EOF
    # Generated by modules/wireless-unifi.nix — do not edit by hand.
    # The container only writes this file when it is absent, so editing it here
    # is how the module stays declarative; your changes would be preserved and
    # then overwritten on the next start.
    db.mongo.local=false
    db.mongo.uri=$uri_base/${wcfg.database.name}?tls=false&authSource=admin
    statdb.mongo.uri=$uri_base/${wcfg.database.name}_stat?tls=false&authSource=admin
    unifi.db.name=${wcfg.database.name}

    # The address APs are told to inform to. Pinned to the LAN gateway because
    # the container is on the host network and would otherwise pick whichever
    # interface it saw first.
    system_ip=${lanGW}
    EOF

    install -m 0640 -o unifi -g unifi "$tmp" ${configDir}/data/system.properties
    rm -f "$tmp"
  '';
in
mkIf wcfg.enable {
  # A STATIC uid/gid pair, which matters twice over: the container is handed
  # them as PUID/PGID and chowns all of /config to them on every start, and a
  # dynamically allocated system user has a null uid at evaluation time, so
  # there would be nothing to hand it. 340 is above everything nixpkgs assigns
  # statically in ids.nix (which currently stops at 327) and below the range
  # NixOS allocates system users from, which counts down from 999.
  users.users.unifi = {
    isSystemUser = true;
    group = "unifi";
    uid = 340;
    home = configDir;
  };
  users.groups.unifi.gid = 340;

  systemd.tmpfiles.rules = [
    "d ${configDir} 0750 unifi unifi -"
    "d ${configDir}/data 0750 unifi unifi -"
    # The official mongo image runs as uid/gid 999.
    "d ${mongoDataDir} 0700 999 999 -"
  ];

  virtualisation.oci-containers.containers = {
    # ── MongoDB ─────────────────────────────────────────
    # No `ports`, and modules/firewall.nix deliberately grants its network no
    # forward rule, so this is reachable from the host and nowhere else.
    unifi-mongo = {
      image = wcfg.database.image;
      # Deliberately NOT labelled for auto-update: a newer major would refuse
      # to start on this data directory and could not be rolled back.
      pull = "missing";
      networks = [ "unifi" ];
      extraOptions = [ "--ip=${dbHost}" ];
      environmentFiles = [ "${w.stateDir}/mongo.env" ];
      volumes = [
        "${mongoDataDir}:/data/db"
        "${mongoInitScript}:/docker-entrypoint-initdb.d/10-unifi.sh:ro"
      ];
      # No --bind_ip: the image's entrypoint adds --bind_ip_all when neither is
      # given, and passing one here would collide with the temporary localhost
      # mongod it runs during the initdb phase. Binding every address inside the
      # container's own netns is not an exposure — no ports are published and
      # the firewall grants this network no forward rule.
      #
      # No --auth either: the entrypoint enables it whenever
      # MONGO_INITDB_ROOT_USERNAME/PASSWORD are set, which the env file does.
      cmd = [
        "--wiredTigerCacheSizeGB"
        wcfg.database.cacheSizeGB
      ];
    };

    # ── Controller ──────────────────────────────────────
    unifi = {
      image = wcfg.image;
      pull = "missing";
      labels."io.containers.autoupdate" = mkIf cfg.wireless.autoUpdate.enable "registry";
      dependsOn = [ "unifi-mongo" ];
      # See the header: UDP broadcast discovery does not survive a bridge.
      extraOptions = [ "--network=host" ];
      volumes = [ "${configDir}:/config" ];
      environment = {
        PUID = toString config.users.users.unifi.uid;
        PGID = toString config.users.groups.unifi.gid;
        TZ = cfg.timeZone;
        MEM_LIMIT = toString wcfg.memoryLimit;
        MEM_STARTUP = toString wcfg.memoryStartup;
        # These are consumed only if system.properties is somehow missing when
        # the container starts; the ExecStartPre below normally beats them to
        # it. Kept consistent so the fallback path is not a broken config.
        MONGO_HOST = dbHost;
        MONGO_PORT = toString dbPort;
        MONGO_DBNAME = wcfg.database.name;
        MONGO_USER = wcfg.database.user;
        MONGO_AUTHSOURCE = "admin";
      };
    };
  };

  systemd.services = {
    "podman-unifi-mongo" = {
      after = [ "router-wireless-secrets.service" ];
      requires = [ "router-wireless-secrets.service" ];
    };

    "podman-unifi" = {
      after = [ "router-wireless-secrets.service" ];
      requires = [ "router-wireless-secrets.service" ];
      # "+" runs as root regardless of the unit's own user, which it needs in
      # order to read the secret and chown into the container's config dir.
      serviceConfig.ExecStartPre = [ "+${systemPropertiesScript}" ];
    };
  };

  # ── DHCP option 43 ────────────────────────────────────
  # Merges into the LAN bridge unit that modules/network.nix defines;
  # dhcpServerConfig is an attrsOf, so network.nix needs no edit.
  #
  # SendVendorOption emits its TLVs encapsulated inside option 43, which is
  # exactly the shape UniFi expects: suboption 1, length 4, IPv4 address. For a
  # gateway of 192.168.1.5 the option payload is 01 04 c0 a8 01 05. If the
  # encapsulation ever needs forcing, the raw equivalent is
  #   SendOption = "43:string:\x01\x04\xc0\xa8\x01\x05";
  systemd.network.networks."40-br-lan".dhcpServerConfig = mkIf wcfg.dhcpOption43 {
    SendVendorOption = "1:ipv4address:${lanGW}";
  };

  # Secondary adoption path: a factory-default device informs to
  # http://unifi:8080/inform. The record goes in the LAN domain itself, not the
  # router's own `<hostName>.<lan.domain>` zone, since that is what a client
  # appending the search domain would resolve.
  router._localDnsRecords = mkIf (wcfg.dnsName != null) [
    {
      zone = cfg.lan.domain;
      name = "${wcfg.dnsName}.${cfg.lan.domain}";
      address = lanGW;
    }
  ];
}
