"""router-ddns — keep Cloudflare DNS records pointed at the router's addresses.

Two kinds of record, both generated by modules/ddns.nix into the config JSON:

  router names  A    → the WAN IPv4 address
                AAAA → the router's own global IPv6 address (the WAN interface's
                       when the ISP gives it one, else the LAN bridge's address
                       from the delegated prefix)
  host names    A    → the WAN IPv4 address (the host is reached through a port
                       forward)
                AAAA → the host's own global IPv6 address: the /64 its bridge
                       currently holds from the delegated prefix, plus the
                       host's configured interface identifier (ipv6Suffix)

The delegated prefix is dynamic, so host addresses are computed rather than
learned: the router never has to have seen the host to publish it.

Records are reconciled to exactly one per name and type, tagged with a comment
so records this tool created can be told apart from hand-made ones. A family
with no usable address this run is left untouched rather than deleted — a
brief prefix-delegation outage must not take the names down with it. A name
dropped from the configuration has its records deleted, but only the ones
carrying the comment.

State directory:
  state.json   — zone-id cache, the managed name set and the last pushed
                 record set (API writes are skipped while it is unchanged and
                 was verified recently)
  status.json  — last run summary for Cockpit, written on success AND failure

Environment overrides (the VM test points them at a fake API):
  ROUTER_DDNS_API_BASE, ROUTER_DDNS_TRACE_URL
"""

from __future__ import annotations

import argparse
import ipaddress
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

API_BASE = os.environ.get("ROUTER_DDNS_API_BASE", "https://api.cloudflare.com/client/v4")
TRACE_URL = os.environ.get("ROUTER_DDNS_TRACE_URL", "https://1.1.1.1/cdn-cgi/trace")
COMMENT = "managed by nixos-router"
VERIFY_INTERVAL = 6 * 3600

# Addresses that cannot be the router's public IPv4: when the WAN holds one of
# these the router sits behind another NAT and must ask the outside world.
# Deliberately not ipaddress.is_global — that also rejects the documentation
# ranges (203.0.113.0/24, …) the VM test uses, and a few real allocations.
NOT_PUBLIC_V4 = [
    ipaddress.ip_network(n)
    for n in (
        "10.0.0.0/8",
        "172.16.0.0/12",
        "192.168.0.0/16",
        "100.64.0.0/10",
        "169.254.0.0/16",
        "127.0.0.0/8",
    )
]
ULA = ipaddress.ip_network("fc00::/7")


class DdnsError(Exception):
    pass


def _iso(ts: float) -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(ts))


def _atomic_write(path: Path, payload: dict, mode: int) -> None:
    tmp = path.with_suffix(".tmp")
    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode)
    with os.fdopen(fd, "w") as handle:
        json.dump(payload, handle, indent=2)
    os.chmod(tmp, mode)
    tmp.rename(path)


# ── Address detection ────────────────────────────────────────────────────────


def _addrs(dev: str, family: int) -> list[dict]:
    """`ip -j addr` entries for one device; empty when it does not exist."""
    proc = subprocess.run(
        ["ip", "-j", f"-{family}", "addr", "show", "dev", dev],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0 or not proc.stdout.strip():
        return []
    return [a for link in json.loads(proc.stdout) for a in link.get("addr_info", [])]


def detect_v4(wan: str) -> tuple[str | None, str]:
    """The public IPv4 address and where it came from ("interface"/"trace")."""
    for a in _addrs(wan, 4):
        if a.get("scope") != "global":
            continue
        addr = ipaddress.ip_address(a["local"])
        if not any(addr in net for net in NOT_PUBLIC_V4):
            return str(addr), "interface"
    # Behind another NAT: Cloudflare's trace endpoint echoes the address the
    # request arrived from. 1.1.1.1 is an IPv4 literal, so it is the IPv4 one.
    try:
        with urllib.request.urlopen(TRACE_URL, timeout=10) as resp:
            body = resp.read().decode()
    except (urllib.error.URLError, OSError) as exc:
        return None, f"trace failed: {exc}"
    for line in body.splitlines():
        if line.startswith("ip="):
            try:
                addr = ipaddress.ip_address(line[3:].strip())
            except ValueError:
                break
            if addr.version == 4:
                return str(addr), "trace"
    return None, "trace returned no IPv4 address"


def _best_v6(dev: str) -> ipaddress.IPv6Interface | None:
    """The device's longest-lived stable global IPv6 address.

    Temporary (privacy) addresses rotate, deprecated ones belong to a prefix
    the ISP has withdrawn, tentative/dadfailed ones are not usable, and ULAs
    are not reachable from the internet. After a prefix change the old address
    lingers deprecated beside the new one, which the lifetime ordering skips.
    """
    usable = [
        a
        for a in _addrs(dev, 6)
        if a.get("scope") == "global"
        and not any(a.get(flag) for flag in ("temporary", "deprecated", "tentative", "dadfailed"))
        and ipaddress.ip_address(a["local"]) not in ULA
    ]
    if not usable:
        return None
    best = max(usable, key=lambda a: a.get("preferred_life_time", 0))
    return ipaddress.IPv6Interface(f"{best['local']}/{best['prefixlen']}")


def detect_router_v6(wan: str, fallback: str) -> str | None:
    iface = _best_v6(wan) or _best_v6(fallback)
    return str(iface.ip) if iface else None


def host_v6(bridge: str, suffix: str) -> str | None:
    """The bridge's current /64 from the delegated prefix, plus the suffix."""
    iface = _best_v6(bridge)
    if iface is None:
        return None
    net64 = ipaddress.ip_network(f"{iface.ip}/64", strict=False)
    return str(ipaddress.IPv6Address(int(net64.network_address) | int(ipaddress.IPv6Address(suffix))))


# ── Cloudflare API ───────────────────────────────────────────────────────────


class Cloudflare:
    def __init__(self, token: str, base: str = API_BASE) -> None:
        self.token = token
        self.base = base.rstrip("/")
        self.writes = 0

    def call(self, method: str, path: str, params: dict | None = None, body: dict | None = None):
        url = f"{self.base}{path}"
        if params:
            url += "?" + urllib.parse.urlencode(params)
        req = urllib.request.Request(
            url,
            data=None if body is None else json.dumps(body).encode(),
            headers={"Authorization": f"Bearer {self.token}", "Content-Type": "application/json"},
            method=method,
        )
        if method != "GET":
            self.writes += 1
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                payload = json.loads(resp.read().decode() or "{}")
        except urllib.error.HTTPError as exc:
            try:
                payload = json.loads(exc.read().decode() or "{}")
            except ValueError:
                raise DdnsError(f"{method} {path}: HTTP {exc.code}") from exc
        except (urllib.error.URLError, OSError) as exc:
            raise DdnsError(f"{method} {path}: {exc}") from exc
        if not payload.get("success", False):
            errors = "; ".join(e.get("message", "?") for e in payload.get("errors", [])) or "request failed"
            raise DdnsError(f"{method} {path}: {errors}")
        return payload.get("result")

    def zone_for(self, name: str, cache: dict) -> str:
        """The id of the zone `name` lives in: the longest suffix that is one.

        Needs Zone:Read on the token. Results are cached in state.json; zone
        ids never change for the life of a zone.
        """
        labels = name.lower().split(".")
        for i in range(len(labels) - 1):
            candidate = ".".join(labels[i:])
            if candidate in cache:
                return cache[candidate]
            found = self.call("GET", "/zones", {"name": candidate, "status": "active"})
            if found:
                cache[candidate] = found[0]["id"]
                return cache[candidate]
        raise DdnsError(f"no Cloudflare zone found for {name} — does the token have Zone:Read on it?")

    def records(self, zone: str, name: str, rtype: str) -> list[dict]:
        return self.call("GET", f"/zones/{zone}/dns_records", {"name": name, "type": rtype}) or []


def reconcile(
    cf: Cloudflare, zone: str, name: str, rtype: str, content: str, ttl: int, proxied: bool
) -> str:
    """Make `name` carry exactly one `rtype` record with `content`."""
    existing = cf.records(zone, name, rtype)
    want = {
        "type": rtype,
        "name": name,
        "content": content,
        "ttl": ttl,
        "proxied": proxied,
        "comment": COMMENT,
    }
    if not existing:
        cf.call("POST", f"/zones/{zone}/dns_records", body=want)
        return "created"
    keep = next((r for r in existing if r.get("comment") == COMMENT), existing[0])
    # A DDNS name holds one address per family; stale extras would keep
    # sending some clients to an address the router no longer has.
    for r in existing:
        if r is not keep:
            cf.call("DELETE", f"/zones/{zone}/dns_records/{r['id']}")
    current = {k: keep.get(k) for k in ("content", "ttl", "proxied", "comment")}
    if current == {k: want[k] for k in current}:
        return "unchanged" if len(existing) == 1 else "updated"
    cf.call("PATCH", f"/zones/{zone}/dns_records/{keep['id']}", body=want)
    return "updated"


def remove_managed(cf: Cloudflare, zone: str, name: str, rtype: str) -> int:
    removed = 0
    for r in cf.records(zone, name, rtype):
        if r.get("comment") == COMMENT:
            cf.call("DELETE", f"/zones/{zone}/dns_records/{r['id']}")
            removed += 1
    return removed


# ── Main ─────────────────────────────────────────────────────────────────────


def _token(cfg: dict) -> str | None:
    cred_dir = os.environ.get("CREDENTIALS_DIRECTORY")
    if cred_dir and (Path(cred_dir) / "cf-api-token").exists():
        return (Path(cred_dir) / "cf-api-token").read_text().strip()
    path = cfg.get("apiTokenFile")
    if path and Path(path).exists():
        return Path(path).read_text().strip()
    return None


def _load(path: Path) -> dict:
    try:
        return json.loads(path.read_text())
    except (OSError, ValueError):
        return {}


def run(cfg: dict, force: bool = False) -> int:
    state_dir = Path(cfg["stateDir"])
    state_dir.mkdir(parents=True, exist_ok=True)
    state_file = state_dir / "state.json"
    status_file = state_dir / "status.json"
    state = _load(state_file)
    now = time.time()

    wan = cfg["wanInterface"]
    v4, v4_source = detect_v4(wan) if cfg.get("ipv4", True) else (None, "disabled")
    router_v6 = detect_router_v6(wan, cfg["routerV6Fallback"]) if cfg.get("ipv6", True) else None

    # Every configured (name, type) — independent of whether an address was
    # found this run, so a family that is briefly unavailable is left alone
    # instead of being treated as removed.
    configured: list[dict] = []
    for rec in cfg["records"]:
        if rec.get("v4"):
            configured.append({**rec, "type": "A", "content": v4})
        v6 = rec.get("v6")
        if v6:
            content = router_v6 if v6["kind"] == "router" else host_v6(v6["interface"], v6["suffix"])
            configured.append({**rec, "type": "AAAA", "content": content})

    desired = {f"{r['name']}/{r['type']}": r["content"] for r in configured if r["content"]}
    configured_keys = sorted({f"{r['name']}/{r['type']}" for r in configured})
    stale = [k for k in state.get("managed", []) if k not in configured_keys]

    results: list[dict] = []
    error: str | None = None
    fresh = now - state.get("lastVerified", 0) < VERIFY_INTERVAL

    if not force and not stale and desired == state.get("lastPushed") and fresh:
        results = [
            {
                "name": r["name"],
                "type": r["type"],
                "host": r.get("host"),
                "content": r["content"],
                "state": "unchanged" if r["content"] else "skipped",
                "detail": "" if r["content"] else "no address this run",
            }
            for r in configured
        ]
    else:
        token = _token(cfg)
        if not token:
            error = "no Cloudflare API token (router.ddns.cloudflare.apiTokenFile)"
        else:
            cf = Cloudflare(token)
            zones = state.setdefault("zones", {})
            for r in configured:
                row = {
                    "name": r["name"],
                    "type": r["type"],
                    "host": r.get("host"),
                    "content": r["content"],
                }
                if not r["content"]:
                    row.update(state="skipped", detail="no address this run — record left as is")
                    results.append(row)
                    continue
                try:
                    zone = cf.zone_for(r["name"], zones)
                    row.update(
                        state=reconcile(
                            cf, zone, r["name"], r["type"], r["content"], cfg["ttl"], cfg["proxied"]
                        ),
                        detail="",
                    )
                except DdnsError as exc:
                    row.update(state="error", detail=str(exc))
                results.append(row)
            for key in stale:
                name, rtype = key.rsplit("/", 1)
                try:
                    removed = remove_managed(cf, cf.zone_for(name, zones), name, rtype)
                    results.append(
                        {"name": name, "type": rtype, "content": None, "state": "removed", "detail": f"{removed} record(s)"}
                    )
                except DdnsError as exc:
                    results.append({"name": name, "type": rtype, "content": None, "state": "error", "detail": str(exc)})
                    configured_keys.append(key)  # keep tracking it; retry next run

            failed = [r for r in results if r["state"] == "error"]
            if failed:
                error = f"{len(failed)} record(s) failed"
            else:
                state["lastPushed"] = desired
                state["lastVerified"] = now
            state["managed"] = sorted(set(configured_keys))
            print(f"router-ddns: {cf.writes} API write(s)", file=sys.stderr)

    _atomic_write(state_file, state, 0o600)
    _atomic_write(
        status_file,
        {
            "lastRun": _iso(now),
            "ok": error is None,
            "error": error,
            "addresses": {"ipv4": v4, "ipv4Source": v4_source, "ipv6": router_v6},
            "records": results,
        },
        0o644,
    )
    for r in results:
        print(f"  {r['state']:9} {r['type']:4} {r['name']} {r.get('content') or ''} {r.get('detail') or ''}".rstrip(), file=sys.stderr)
    if error:
        print(f"router-ddns: {error}", file=sys.stderr)
        return 1
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description="Update Cloudflare DNS records with the router's addresses")
    parser.add_argument("--config", required=True, help="runtime config JSON (Nix-generated)")
    parser.add_argument("--force", action="store_true", help="verify every record even if nothing changed")
    args = parser.parse_args()
    cfg = json.loads(Path(args.config).read_text())["ddns"]
    sys.exit(run(cfg, force=args.force))


if __name__ == "__main__":
    main()
