"""router-ddns — keep Cloudflare DNS records pointed at the router's addresses.

Two kinds of record, both generated by modules/ddns.nix into the config JSON:

  router names  A    → the WAN IPv4 address
                AAAA → the router's own global IPv6 address (the WAN interface's
                       when the ISP gives it one, else the LAN bridge's address
                       from the delegated prefix)
  host names    A    → the WAN IPv4 address (the host is reached through a port
                       forward)
                AAAA → the host's own global IPv6 address: the /64 its bridge
                       currently holds from the delegated prefix, plus the
                       host's configured interface identifier (ipv6Suffix)

The delegated prefix is dynamic, so host addresses are computed rather than
learned: the router never has to have seen the host to publish it.

Records are reconciled to exactly one per name and type, tagged with a comment
so records this tool created can be told apart from hand-made ones. A family
with no usable address this run is left untouched rather than deleted — a
brief prefix-delegation outage must not take the names down with it. A name
dropped from the configuration has its records deleted, but only the ones
carrying the comment.

A configured name belongs to the router: an A/AAAA record already there is
overwritten, and a CNAME — which DNS allows nothing else beside — is replaced.
The replaced CNAME is kept in state.json and put back when the name is dropped
from the configuration, so taking a name over is never a one-way loss.

enable=false drops every name: the managed records are deleted and the
replaced CNAMEs restored, without looking up any address. A disabled run with
nothing recorded to tear down does nothing at all, and one over state no
enabled run has stamped with STATE_VERSION only reports it: that state was
left by a version that kept the records when turned off, and said so, so
they stay until the owner turns dynamic DNS on and then off again.

State directory:
  state.json   — zone cache, the managed name set, the last pushed record
                 set with its TTL and proxying (API writes are skipped while
                 it is unchanged and was verified recently), the CNAMEs
                 replaced to take names over and the state version
  status.json  — last run summary for Cockpit, written on success AND failure

Environment overrides (the VM test points them at a fake API):
  ROUTER_CLOUDFLARE_API_BASE (or ROUTER_DDNS_API_BASE), ROUTER_DDNS_TRACE_URL
"""

from __future__ import annotations

import argparse
import ipaddress
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

from .cloudflare import (
    COMMENT,
    Cloudflare,
    CloudflareError,
    load_json,
    load_token,
    restore,
    write_json,
)
from .cloudflare import take_over as _take_over

TRACE_URL = os.environ.get("ROUTER_DDNS_TRACE_URL", "https://1.1.1.1/cdn-cgi/trace")
VERIFY_INTERVAL = 6 * 3600

# Stamped into state.json by every enabled run. Version 2 is the first whose
# disabled runs delete the records; state without the stamp was last written
# by a version that promised turning dynamic DNS off would keep them.
STATE_VERSION = 2
LEGACY_NOTE = (
    "records from before the upgrade are left in Cloudflare, since turning dynamic DNS off used to keep them"
    " — to delete them, turn dynamic DNS on and apply, then turn it off and apply again"
)

# Addresses that cannot be the router's public IPv4: when the WAN holds one of
# these the router sits behind another NAT and must ask the outside world.
# Deliberately not ipaddress.is_global — that also rejects the documentation
# ranges (203.0.113.0/24, …) the VM test uses, and a few real allocations.
NOT_PUBLIC_V4 = [
    ipaddress.ip_network(n)
    for n in (
        "10.0.0.0/8",
        "172.16.0.0/12",
        "192.168.0.0/16",
        "100.64.0.0/10",
        "169.254.0.0/16",
        "127.0.0.0/8",
    )
]
ULA = ipaddress.ip_network("fc00::/7")


def _iso(ts: float) -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(ts))


# ── Address detection ────────────────────────────────────────────────────────


def _addrs(dev: str, family: int) -> list[dict]:
    """`ip -j addr` entries for one device; empty when it does not exist."""
    proc = subprocess.run(
        ["ip", "-j", f"-{family}", "addr", "show", "dev", dev],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0 or not proc.stdout.strip():
        return []
    return [a for link in json.loads(proc.stdout) for a in link.get("addr_info", [])]


def detect_v4(wan: str) -> tuple[str | None, str]:
    """The public IPv4 address and where it came from ("interface"/"trace")."""
    for a in _addrs(wan, 4):
        if a.get("scope") != "global":
            continue
        addr = ipaddress.ip_address(a["local"])
        if not any(addr in net for net in NOT_PUBLIC_V4):
            return str(addr), "interface"
    # Behind another NAT: Cloudflare's trace endpoint echoes the address the
    # request arrived from. 1.1.1.1 is an IPv4 literal, so it is the IPv4 one.
    try:
        with urllib.request.urlopen(TRACE_URL, timeout=10) as resp:
            body = resp.read().decode()
    except (urllib.error.URLError, OSError) as exc:
        return None, f"trace failed: {exc}"
    for line in body.splitlines():
        if line.startswith("ip="):
            try:
                addr = ipaddress.ip_address(line[3:].strip())
            except ValueError:
                break
            if addr.version == 4:
                return str(addr), "trace"
    return None, "trace returned no IPv4 address"


def _best_v6(dev: str) -> ipaddress.IPv6Interface | None:
    """The device's longest-lived stable global IPv6 address.

    Temporary (privacy) addresses rotate, deprecated ones belong to a prefix
    the ISP has withdrawn, tentative/dadfailed ones are not usable, and ULAs
    are not reachable from the internet. After a prefix change the old address
    lingers deprecated beside the new one, which the lifetime ordering skips.
    """
    usable = [
        a
        for a in _addrs(dev, 6)
        if a.get("scope") == "global"
        and not any(a.get(flag) for flag in ("temporary", "deprecated", "tentative", "dadfailed"))
        and ipaddress.ip_address(a["local"]) not in ULA
    ]
    if not usable:
        return None
    best = max(usable, key=lambda a: a.get("preferred_life_time", 0))
    return ipaddress.IPv6Interface(f"{best['local']}/{best['prefixlen']}")


def detect_router_v6(wan: str, fallback: str) -> str | None:
    iface = _best_v6(wan) or _best_v6(fallback)
    return str(iface.ip) if iface else None


def host_v6(bridge: str, suffix: str) -> str | None:
    """The bridge's current /64 from the delegated prefix, plus the suffix."""
    iface = _best_v6(bridge)
    if iface is None:
        return None
    net64 = ipaddress.ip_network(f"{iface.ip}/64", strict=False)
    return str(ipaddress.IPv6Address(int(net64.network_address) | int(ipaddress.IPv6Address(suffix))))


# ── Cloudflare API ───────────────────────────────────────────────────────────


def take_over(cf: Cloudflare, zone: str, name: str, replaced: dict) -> str:
    """Clear `name` of CNAMEs, which DNS allows no other record beside.

    Each one is remembered in `replaced` (persisted in state.json) so it can be
    restored when the name leaves the configuration. Returns a note for the
    status file, or "" when there was nothing to replace.
    """
    removed = _take_over(cf, zone, name, replaced, ("CNAME",))
    return "; ".join(f"replaced CNAME → {r.get('content')} (restored if the name is dropped)" for r in removed)


def reconcile(
    cf: Cloudflare,
    zone: str,
    name: str,
    rtype: str,
    content: str,
    ttl: int,
    proxied: bool,
    replaced: dict,
) -> tuple[str, str]:
    """Make `name` carry exactly one `rtype` record with `content`.

    Returns the outcome and a note for the status file.
    """
    existing = cf.records(zone, name, rtype)
    want = {
        "type": rtype,
        "name": name,
        "content": content,
        "ttl": ttl,
        "proxied": proxied,
        "comment": COMMENT,
    }
    if not existing:
        # No address record of this type yet, so a CNAME may be holding the
        # name (with one present, none can be).
        note = take_over(cf, zone, name, replaced)
        cf.call("POST", f"/zones/{zone}/dns_records", body=want)
        return "created", note
    keep = next((r for r in existing if r.get("comment") == COMMENT), existing[0])
    # A DDNS name holds one address per family; stale extras would keep
    # sending some clients to an address the router no longer has.
    for r in existing:
        if r is not keep:
            cf.call("DELETE", f"/zones/{zone}/dns_records/{r['id']}")
    current = {k: keep.get(k) for k in ("content", "ttl", "proxied", "comment")}
    if current == {k: want[k] for k in current}:
        return ("unchanged" if len(existing) == 1 else "updated"), ""
    cf.call("PATCH", f"/zones/{zone}/dns_records/{keep['id']}", body=want)
    return "updated", ""


def remove_managed(cf: Cloudflare, zone: str, name: str, rtype: str) -> int:
    removed = 0
    for r in cf.records(zone, name, rtype):
        if r.get("comment") == COMMENT:
            cf.call("DELETE", f"/zones/{zone}/dns_records/{r['id']}")
            removed += 1
    return removed


# ── Main ─────────────────────────────────────────────────────────────────────


def run(cfg: dict, force: bool = False) -> int:
    state_dir = Path(cfg["stateDir"])
    state_file = state_dir / "state.json"
    status_file = state_dir / "status.json"
    enable = cfg.get("enable", True)

    state = load_json(state_file)
    if not enable and not (state.get("managed") or state.get("replaced")):
        return 0  # never enabled, or already torn down
    state_dir.mkdir(parents=True, exist_ok=True)
    now = time.time()

    if not enable and state.get("version", 1) < STATE_VERSION:
        # Turned off before the upgrade: leave Cloudflare (and state.json,
        # still the only copy of the replaced CNAMEs) exactly as they are.
        print(f"router-ddns: {LEGACY_NOTE}", file=sys.stderr)
        write_json(
            status_file,
            {
                "lastRun": _iso(now),
                "ok": True,
                "error": None,
                "addresses": {"ipv4": None, "ipv4Source": "disabled", "ipv6": None},
                "records": [],
                "message": LEGACY_NOTE,
            },
            0o644,
        )
        return 0

    if enable:
        state["version"] = STATE_VERSION
        wan = cfg["wanInterface"]
        v4, v4_source = detect_v4(wan) if cfg.get("ipv4", True) else (None, "disabled")
        router_v6 = detect_router_v6(wan, cfg["routerV6Fallback"]) if cfg.get("ipv6", True) else None
    else:
        # Tearing down needs no address: with nothing configured, every
        # managed record is stale and every replaced CNAME is restored below.
        v4, v4_source, router_v6 = None, "disabled", None

    # Every configured (name, type) — independent of whether an address was
    # found this run, so a family that is briefly unavailable is left alone
    # instead of being treated as removed.
    configured: list[dict] = []
    for rec in cfg["records"] if enable else []:
        if rec.get("v4"):
            configured.append({**rec, "type": "A", "content": v4})
        v6 = rec.get("v6")
        if v6:
            content = router_v6 if v6["kind"] == "router" else host_v6(v6["interface"], v6["suffix"])
            configured.append({**rec, "type": "AAAA", "content": content})

    # TTL and proxying are part of the fingerprint, so a change to either
    # alone reaches Cloudflare now rather than at the next full check.
    desired = {f"{r['name']}/{r['type']}": [r["content"], cfg["ttl"], cfg["proxied"]] for r in configured if r["content"]}
    configured_keys = sorted({f"{r['name']}/{r['type']}" for r in configured})
    stale = [k for k in state.get("managed", []) if k not in configured_keys]
    # Names taken over from a CNAME that are no longer configured: put it back.
    replaced = state.setdefault("replaced", {})
    configured_names = {r["name"] for r in configured}
    to_restore = [n for n in replaced if n not in configured_names]

    results: list[dict] = []
    error: str | None = None
    fresh = now - state.get("lastVerified", 0) < VERIFY_INTERVAL

    if not force and not stale and not to_restore and desired == state.get("lastPushed") and fresh:
        results = [
            {
                "name": r["name"],
                "type": r["type"],
                "host": r.get("host"),
                "content": r["content"],
                "state": "unchanged" if r["content"] else "skipped",
                "detail": "" if r["content"] else "no address this run",
            }
            for r in configured
        ]
    else:
        token = load_token(cfg.get("apiTokenFile"))
        if not token:
            error = "no Cloudflare API token (router.ddns.cloudflare.apiTokenFile)"
        else:
            cf = Cloudflare(token)
            zones = state.setdefault("zones", {})
            for r in configured:
                row = {
                    "name": r["name"],
                    "type": r["type"],
                    "host": r.get("host"),
                    "content": r["content"],
                }
                if not r["content"]:
                    row.update(state="skipped", detail="no address this run — record left as is")
                    results.append(row)
                    continue
                try:
                    zone = cf.zone_for(r["name"], zones)["id"]
                    outcome, note = reconcile(
                        cf,
                        zone,
                        r["name"],
                        r["type"],
                        r["content"],
                        cfg["ttl"],
                        cfg["proxied"],
                        replaced,
                    )
                    row.update(state=outcome, detail=note)
                except CloudflareError as exc:
                    row.update(state="error", detail=str(exc))
                results.append(row)
            for key in stale:
                name, rtype = key.rsplit("/", 1)
                try:
                    removed = remove_managed(cf, cf.zone_for(name, zones)["id"], name, rtype)
                    results.append(
                        {"name": name, "type": rtype, "content": None, "state": "removed", "detail": f"{removed} record(s)"}
                    )
                except CloudflareError as exc:
                    results.append({"name": name, "type": rtype, "content": None, "state": "error", "detail": str(exc)})
                    configured_keys.append(key)  # keep tracking it; retry next run
            # Restore only where this tool's records are gone: a name whose
            # removal failed above is still tracked, and is retried next run.
            tracked = {k.rsplit("/", 1)[0] for k in configured_keys}
            for name in to_restore:
                if name in tracked:
                    continue
                try:
                    zone = cf.zone_for(name, zones)["id"]
                    # Also clears records left from a run whose state was lost.
                    for rtype in ("A", "AAAA"):
                        remove_managed(cf, zone, name, rtype)
                    created = restore(cf, zone, replaced[name])
                    for rec in replaced.pop(name):
                        new = any(c is rec for c in created)
                        results.append(
                            {
                                "name": name,
                                "type": rec.get("type"),
                                "content": rec.get("content"),
                                "state": "created" if new else "unchanged",
                                "detail": f"{'restored' if new else 'already back'}: the name is no longer configured",
                            }
                        )
                except CloudflareError as exc:
                    results.append(
                        {"name": name, "type": "CNAME", "content": None, "state": "error", "detail": f"restoring the replaced record: {exc}"}
                    )

            failed = [r for r in results if r["state"] == "error"]
            if failed:
                error = f"{len(failed)} record(s) failed"
            else:
                state["lastPushed"] = desired
                state["lastVerified"] = now
            state["managed"] = sorted(set(configured_keys))
            print(f"router-ddns: {cf.writes} API write(s)", file=sys.stderr)

    write_json(state_file, state, 0o600)
    write_json(
        status_file,
        {
            "lastRun": _iso(now),
            "ok": error is None,
            "error": error,
            "addresses": {"ipv4": v4, "ipv4Source": v4_source, "ipv6": router_v6},
            "records": results,
        },
        0o644,
    )
    for r in results:
        print(f"  {r['state']:9} {r['type']:4} {r['name']} {r.get('content') or ''} {r.get('detail') or ''}".rstrip(), file=sys.stderr)
    if error:
        print(f"router-ddns: {error}", file=sys.stderr)
        return 1
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description="Update Cloudflare DNS records with the router's addresses")
    parser.add_argument("--config", required=True, help="runtime config JSON (Nix-generated)")
    parser.add_argument("--force", action="store_true", help="verify every record even if nothing changed")
    args = parser.parse_args()
    cfg = json.loads(Path(args.config).read_text())["ddns"]
    sys.exit(run(cfg, force=args.force))


if __name__ == "__main__":
    main()
