"""Compile router access policies into Technitium Advanced Blocking config.

Inputs:
  • static inputs JSON generated by Nix (modules/access-policies.nix):
    policies with catalog URLs pre-expanded and format-tagged, the device
    registry, host group names, network CIDRs, DoH base layer, block page.
  • directory state JSON written by router-directory-sync (optional).

Output: the Advanced Blocking `dnsApp.config` JSON object.

Precedence (one winning policy per client — the app maps each client to
exactly one group, most-specific networkGroupMap prefix wins):
  host group > directory group (of the device's user) > subnet/network >
  defaultPolicy; within a tier the highest `priority` wins.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

BYPASS_GROUP = "bypass"
STALE_DIRECTORY_S = 7 * 24 * 3600


def _load_directory(path: str | None) -> dict | None:
    if not path:
        return None
    try:
        directory = json.loads(Path(path).read_text())
    except FileNotFoundError:
        print("directory state missing — user-tier assignments inactive", file=sys.stderr)
        return None
    except (OSError, ValueError) as exc:
        print(f"directory state unreadable ({exc}) — user-tier assignments inactive", file=sys.stderr)
        return None
    synced = directory.get("syncedAt")
    if synced:
        try:
            from datetime import datetime, timezone

            age = time.time() - datetime.fromisoformat(synced.replace("Z", "+00:00")).timestamp()
            if age > STALE_DIRECTORY_S:
                print(f"directory state is {age / 86400:.1f} days old — compiling with last-good data", file=sys.stderr)
        except ValueError:
            pass
    return directory


def _user_group_keys(directory: dict, user_ref: str) -> set[str]:
    """All identifiers (ids and names, lowercased) of the groups a user belongs to."""
    ref = user_ref.lower()
    user = next(
        (u for u in directory.get("users", []) if ref in {str(u.get("id", "")).lower(), str(u.get("email", "")).lower()}),
        None,
    )
    if user is None:
        return set()
    member_ids = {str(g).lower() for g in user.get("groups", [])}
    keys = set(member_ids)
    for group in directory.get("groups", []):
        if str(group.get("id", "")).lower() in member_ids:
            keys.add(str(group.get("name", "")).lower())
    return keys


def _pick(policies: list[dict]) -> dict | None:
    return max(policies, key=lambda p: p["priority"]) if policies else None


def _group_for(policy: dict, static: dict) -> dict:
    block_page = static.get("blockPage", {})
    blocking_addresses = list(policy["blockingAddresses"])
    if block_page.get("enable") and policy["responseType"] == "blockingAddress":
        blocking_addresses = [static["networks"]["lan"]["gateway"]]
    blocked = list(policy["blocked"])
    if static.get("blockDoHProviders", True):
        blocked += [d for d in static.get("dohProviderDomains", []) if d not in blocked]
    return {
        "name": policy["name"],
        "enableBlocking": True,
        "allowTxtBlockingReport": True,
        "blockAsNxDomain": policy["responseType"] == "nxdomain",
        "blockingAddresses": blocking_addresses,
        "allowed": sorted(policy["allowed"]),
        "blocked": sorted(blocked),
        "allowListUrls": policy["allowListUrls"],
        "blockListUrls": policy["blockListUrls"],
        "allowedRegex": policy["allowedRegex"],
        "blockedRegex": policy["blockedRegex"],
        "regexAllowListUrls": [],
        "regexBlockListUrls": policy["regexBlockListUrls"],
        "adblockListUrls": policy["adblockListUrls"],
    }


def compile_config(static: dict, directory: dict | None) -> dict:
    policies = static["policies"]
    by_priority = sorted(policies, key=lambda p: p["priority"])  # ascending: later writes win

    network_map: dict[str, str] = {
        "0.0.0.0/0": static["defaultPolicy"],
        "[::]/0": static["defaultPolicy"],
        "127.0.0.0/8": BYPASS_GROUP,
        "[::1]": BYPASS_GROUP,
    }

    # ── network / subnet tier ────────────────────────────────
    nets = static["networks"]
    net_cidrs = {
        "lan": [nets["lan"]["cidr"]],
        "guest": [nets["guest"]["cidr"]] if nets.get("guest", {}).get("cidr") else [],
        "wireguard": nets.get("wireguard", []),
    }
    for policy in by_priority:
        for net in policy["assignments"]["networks"]:
            for cidr in net_cidrs.get(net, []):
                network_map[cidr] = policy["name"]
        for cidr in policy["assignments"]["subnets"]:
            network_map[cidr] = policy["name"]

    # ── device tier (one entry max per pinned device) ────────
    for host in static["hosts"]:
        ip = host.get("staticIp")
        if not ip:
            continue  # unpinned devices follow the CIDR tiers
        winner = None
        if host.get("group"):
            winner = _pick([p for p in policies if host["group"] in p["assignments"]["hostGroups"]])
        if winner is None and host.get("user") and directory:
            user_keys = _user_group_keys(directory, host["user"])
            winner = _pick(
                [
                    p
                    for p in policies
                    if user_keys & {str(g).lower() for g in p["assignments"]["directoryGroups"]}
                ]
            )
        if winner is not None:
            network_map[ip] = winner["name"]

    groups = [_group_for(p, static) for p in sorted(policies, key=lambda p: p["name"])]
    groups.append(
        {
            "name": BYPASS_GROUP,
            "enableBlocking": False,
            "allowTxtBlockingReport": True,
            "blockAsNxDomain": False,
            "blockingAddresses": [],
            "allowed": [],
            "blocked": [],
            "allowListUrls": [],
            "blockListUrls": [],
            "allowedRegex": [],
            "blockedRegex": [],
            "regexAllowListUrls": [],
            "regexBlockListUrls": [],
            "adblockListUrls": [],
        }
    )

    return {
        "enableBlocking": True,
        "blockingAnswerTtl": 30,
        "blockListUrlUpdateIntervalHours": 24,
        "blockListUrlUpdateIntervalMinutes": 0,
        "localEndPointGroupMap": {},
        "networkGroupMap": network_map,
        "groups": groups,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Compile access policies to Advanced Blocking config")
    parser.add_argument("--static", required=True, help="router-policy-static.json path")
    parser.add_argument("--directory", help="directory.json path (optional)")
    args = parser.parse_args()

    static = json.loads(Path(args.static).read_text())
    directory = _load_directory(args.directory)
    json.dump(compile_config(static, directory), sys.stdout, indent=2, sort_keys=False)
    print()


if __name__ == "__main__":
    main()
